apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksmanualconfig-5a3b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksmanualconfig-5a3b"
  template:
    metadata:
      labels:
        app: "aksmanualconfig-5a3b"
    spec:
      containers:
        - name: "aksmanualconfig-5a3b"
          image: "aksmanualtestacr.azurecr.io/aksmanualconfig"
          ports:
          - containerPort: 80