apiVersion: v1
kind: Service
metadata:
    name: "aksmanualconfig-5a3b"
    labels:
        app: "aksmanualconfig-5a3b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksmanualconfig-5a3b"