on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aksmanualtestacr -g aksmanualtestacr849e-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aksmanualtestacr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aksmanualtestacr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aksmanualtestacr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: aksmanualtestacr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t aksmanualtestacr.azurecr.io/aksmanualconfig:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push aksmanualtestacr.azurecr.io/aksmanualconfig:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aksmanualconfig_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: aksmanualtestacr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aksmanualcondockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksmanualtestacr.azurecr.io/aksmanualconfig:${{ github.sha }}
        imagepullsecrets: |
          aksmanualcondockerauth   
